### ISSUE TITLE
to bring p. 1.5 (Destructors) of this article in accordance with the latest EO version

### ISSUE THREAD

**Issue by Graur** [objectionary/reducing-programs-to-objects#7]
We need to make sure that all code snippets in p. 1.5 (Destructors) run successfully. And the description does not contradict the description in other articles: https://arxiv.org/pdf/2206.02585.pdf and https://arxiv.org/pdf/2111.13384.pdf

**Comment by Graur** [comment]
@MCJOHN974 please, help us here

**Comment by Graur** [comment]
@MCJOHN974 What about the progress of this task? Do you need some help?

**Comment by MCJOHN974** [comment]
I found that code in paper don't work. I rewrited it as follows:
```
+package sandbox
+version 0.0.0

[] > foo
  nop > @
  [] > constructor
    QQ.io.stdout "Alive" > @
  [] > destructor
    QQ.io.stdout "Dead" > @

[] > main
  foo > f
  seq > @
    f.constructor
    f.destructor
```
I decided do not make a difference between constructor and destructor. My code compiles, but fails in runtime

**Comment by MCJOHN974** [comment]
I run it using the objectionary/sandbox

**Comment by Graur** [comment]
@MCJOHN974 Can you post a stack trace here?

**Comment by MCJOHN974** [comment]
```
Exception in thread "main" java.lang.ClassNotFoundException: EOsandbox.EOapp
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.eolang.Main.run(Main.java:181)
        at org.eolang.Main.main(Main.java:98)
        ```

**Comment by MCJOHN974** [comment]
@Graur is it the trace you asked ?

**Comment by Graur** [comment]
@MCJOHN974 Yes, I think you run `.sh` script, which should call `app` class. But there is no `app` class in your directory, just `foo` and `main`.

Also, this task is urgent, would be great if you put it to the highest priority
