### ISSUE TITLE
to bring p. 1.8 (Generators) and p. 1.9 (Types and Type Casting) of this article in accordance with the latest EO version

### ISSUE THREAD

**Issue by Graur** [objectionary/reducing-programs-to-objects#9]
We need to make sure that all code snippets in p. 1.8 (Generators) and p. 1.9 (Types and Type Casting) run successfully. And the description does not contradict the description in other articles: https://arxiv.org/pdf/2206.02585.pdf and https://arxiv.org/pdf/2111.13384.pdf

**Comment by Graur** [comment]
@ivan-egorov42 please, help us here

**Comment by ivan-egorov42** [comment]
@Graur I tried to change it. Now it works and I get first ten Fibonacci numbers as it should be, but in the end of the execution there is an exception. Now, I have no ideas, could you take a look please?

Here is my code:

```
[limit f] > fibonacci
  memory 0 > a
  memory 0 > b
  memory 0 > i
  seq > @
    a.write 1
    b.write 1
    f 0
    while.
      seq (i.write (i.plus 1)) (i.lt limit)
      [idx]
        seq > @
          b.write (a.plus b)
          a.write (b.minus a)
          f (b.minus a)

[] > test
  fibonacci > @
    10
    [n]
      QQ.io.stdout > @
        QQ.txt.sprintf
          "%d\n"
          n
```
Here is output:

```
0
1
1
2
3
5
8
13
21
34
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.Long to java.lang.Boolean
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.eolang.Dataized.take(Dataized.java:127)
	at org.eolang.Main.run(Main.java:190)
	at org.eolang.Main.main(Main.java:98)
```

**Comment by Graur** [comment]
@ivan-egorov42 Are you using `+junit` meta? If so, perhaps the `fibonacci` object returns a successful number of `while` loops, which is `9`. But the `test` object must return either `bool` or `string` object.

**Comment by ivan-egorov42** [comment]
@Graur thanks!) It seems better now. Here is test for code snippet, I'll make a PR.

```
[limit f] > fibonacci
  memory 0 > a
  memory 0 > b
  memory 0 > i
  seq > @
    a.write 1
    b.write 1
    f 0
    while.
      seq (i.write (i.plus 1)) (i.lt limit)
      [idx]
        seq > @
          b.write (a.plus b)
          a.write (b.minus a)
          f (b.minus a)
    TRUE

[] > test
  fibonacci > @
    10
    [n]
      QQ.io.stdout > @
        QQ.txt.sprintf
          "%d\n"
          n
```

**Comment by Graur** [comment]
@ivan-egorov42 Thanks!

**Comment by Graur** [comment]
Test:
```
[] > check
  [] > original-cart
    memory 0 > total
    [b] > add
      total.write (total.plus (b.price))
  [] > cart
    original-cart > @
    [b] > add
      if. > @
        b.subtype-of (QQ.txt.text "Book")
        ^.@.add b
        error "Type mismatch, Book expected"
  [] > original-book
    memory 0 > price
  [] > book
    original-book > @
    [t] > subtype-of
      t.eq "Book" > @
    [] > price
      ^.@.price > @
  assert-that > @
    cart.add book
    $.equal-to TRUE
```
